/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alternating_Decoder_6 (
    input [511:0] dataIn,
    output reg [6143:0] out
  );
  
  
  
  localparam COLORS = 72'he89894a2fba2000000;
  
  reg [6143:0] array;
  
  reg [6143:0] reversedArray;
  
  integer i;
  
  always @* begin
    for (i = 1'h0; i < 9'h100; i = i + 1) begin
      if (dataIn[(i)*2+1-:2] == 2'h0) begin
        array[(i)*24+23-:24] = 24'h000000;
      end
      if (dataIn[(i)*2+1-:2] == 2'h1) begin
        array[(i)*24+23-:24] = 24'ha2fba2;
      end
      if (dataIn[(i)*2+1-:2] == 2'h2) begin
        array[(i)*24+23-:24] = 24'he89894;
      end else begin
        array[(i)*24+23-:24] = 24'h0000ff;
      end
    end
    reversedArray[0+383-:384] = array[0+383-:384];
    reversedArray[0+383-:384] = array[0+383-:384];
    reversedArray[768+383-:384] = array[768+383-:384];
    reversedArray[1536+383-:384] = array[1536+383-:384];
    reversedArray[2304+383-:384] = array[2304+383-:384];
    reversedArray[3072+383-:384] = array[3072+383-:384];
    reversedArray[3840+383-:384] = array[3840+383-:384];
    reversedArray[4608+383-:384] = array[4608+383-:384];
    reversedArray[5376+383-:384] = array[5376+383-:384];
    reversedArray[384+23-:24] = array[744+23-:24];
    reversedArray[408+23-:24] = array[720+23-:24];
    reversedArray[432+23-:24] = array[696+23-:24];
    reversedArray[456+23-:24] = array[672+23-:24];
    reversedArray[480+23-:24] = array[648+23-:24];
    reversedArray[504+23-:24] = array[624+23-:24];
    reversedArray[528+23-:24] = array[600+23-:24];
    reversedArray[552+23-:24] = array[576+23-:24];
    reversedArray[576+23-:24] = array[552+23-:24];
    reversedArray[600+23-:24] = array[528+23-:24];
    reversedArray[624+23-:24] = array[504+23-:24];
    reversedArray[648+23-:24] = array[480+23-:24];
    reversedArray[672+23-:24] = array[456+23-:24];
    reversedArray[696+23-:24] = array[432+23-:24];
    reversedArray[720+23-:24] = array[408+23-:24];
    reversedArray[744+23-:24] = array[384+23-:24];
    reversedArray[1152+23-:24] = array[1512+23-:24];
    reversedArray[1176+23-:24] = array[1488+23-:24];
    reversedArray[1200+23-:24] = array[1464+23-:24];
    reversedArray[1224+23-:24] = array[1440+23-:24];
    reversedArray[1248+23-:24] = array[1416+23-:24];
    reversedArray[1272+23-:24] = array[1392+23-:24];
    reversedArray[1296+23-:24] = array[1368+23-:24];
    reversedArray[1320+23-:24] = array[1344+23-:24];
    reversedArray[1344+23-:24] = array[1320+23-:24];
    reversedArray[1368+23-:24] = array[1296+23-:24];
    reversedArray[1392+23-:24] = array[1272+23-:24];
    reversedArray[1416+23-:24] = array[1248+23-:24];
    reversedArray[1440+23-:24] = array[1224+23-:24];
    reversedArray[1464+23-:24] = array[1200+23-:24];
    reversedArray[1488+23-:24] = array[1176+23-:24];
    reversedArray[1512+23-:24] = array[1152+23-:24];
    reversedArray[1920+23-:24] = array[2280+23-:24];
    reversedArray[1944+23-:24] = array[2256+23-:24];
    reversedArray[1968+23-:24] = array[2232+23-:24];
    reversedArray[1992+23-:24] = array[2208+23-:24];
    reversedArray[2016+23-:24] = array[2184+23-:24];
    reversedArray[2040+23-:24] = array[2160+23-:24];
    reversedArray[2064+23-:24] = array[2136+23-:24];
    reversedArray[2088+23-:24] = array[2112+23-:24];
    reversedArray[2112+23-:24] = array[2088+23-:24];
    reversedArray[2136+23-:24] = array[2064+23-:24];
    reversedArray[2160+23-:24] = array[2040+23-:24];
    reversedArray[2184+23-:24] = array[2016+23-:24];
    reversedArray[2208+23-:24] = array[1992+23-:24];
    reversedArray[2232+23-:24] = array[1968+23-:24];
    reversedArray[2256+23-:24] = array[1944+23-:24];
    reversedArray[2280+23-:24] = array[1920+23-:24];
    reversedArray[2688+23-:24] = array[3048+23-:24];
    reversedArray[2712+23-:24] = array[3024+23-:24];
    reversedArray[2736+23-:24] = array[3000+23-:24];
    reversedArray[2760+23-:24] = array[2976+23-:24];
    reversedArray[2784+23-:24] = array[2952+23-:24];
    reversedArray[2808+23-:24] = array[2928+23-:24];
    reversedArray[2832+23-:24] = array[2904+23-:24];
    reversedArray[2856+23-:24] = array[2880+23-:24];
    reversedArray[2880+23-:24] = array[2856+23-:24];
    reversedArray[2904+23-:24] = array[2832+23-:24];
    reversedArray[2928+23-:24] = array[2808+23-:24];
    reversedArray[2952+23-:24] = array[2784+23-:24];
    reversedArray[2976+23-:24] = array[2760+23-:24];
    reversedArray[3000+23-:24] = array[2736+23-:24];
    reversedArray[3024+23-:24] = array[2712+23-:24];
    reversedArray[3048+23-:24] = array[2688+23-:24];
    reversedArray[3456+23-:24] = array[3816+23-:24];
    reversedArray[3480+23-:24] = array[3792+23-:24];
    reversedArray[3504+23-:24] = array[3768+23-:24];
    reversedArray[3528+23-:24] = array[3744+23-:24];
    reversedArray[3552+23-:24] = array[3720+23-:24];
    reversedArray[3576+23-:24] = array[3696+23-:24];
    reversedArray[3600+23-:24] = array[3672+23-:24];
    reversedArray[3624+23-:24] = array[3648+23-:24];
    reversedArray[3648+23-:24] = array[3624+23-:24];
    reversedArray[3672+23-:24] = array[3600+23-:24];
    reversedArray[3696+23-:24] = array[3576+23-:24];
    reversedArray[3720+23-:24] = array[3552+23-:24];
    reversedArray[3744+23-:24] = array[3528+23-:24];
    reversedArray[3768+23-:24] = array[3504+23-:24];
    reversedArray[3792+23-:24] = array[3480+23-:24];
    reversedArray[3816+23-:24] = array[3456+23-:24];
    reversedArray[4224+23-:24] = array[4584+23-:24];
    reversedArray[4248+23-:24] = array[4560+23-:24];
    reversedArray[4272+23-:24] = array[4536+23-:24];
    reversedArray[4296+23-:24] = array[4512+23-:24];
    reversedArray[4320+23-:24] = array[4488+23-:24];
    reversedArray[4344+23-:24] = array[4464+23-:24];
    reversedArray[4368+23-:24] = array[4440+23-:24];
    reversedArray[4392+23-:24] = array[4416+23-:24];
    reversedArray[4416+23-:24] = array[4392+23-:24];
    reversedArray[4440+23-:24] = array[4368+23-:24];
    reversedArray[4464+23-:24] = array[4344+23-:24];
    reversedArray[4488+23-:24] = array[4320+23-:24];
    reversedArray[4512+23-:24] = array[4296+23-:24];
    reversedArray[4536+23-:24] = array[4272+23-:24];
    reversedArray[4560+23-:24] = array[4248+23-:24];
    reversedArray[4584+23-:24] = array[4224+23-:24];
    reversedArray[4992+23-:24] = array[5352+23-:24];
    reversedArray[5016+23-:24] = array[5328+23-:24];
    reversedArray[5040+23-:24] = array[5304+23-:24];
    reversedArray[5064+23-:24] = array[5280+23-:24];
    reversedArray[5088+23-:24] = array[5256+23-:24];
    reversedArray[5112+23-:24] = array[5232+23-:24];
    reversedArray[5136+23-:24] = array[5208+23-:24];
    reversedArray[5160+23-:24] = array[5184+23-:24];
    reversedArray[5184+23-:24] = array[5160+23-:24];
    reversedArray[5208+23-:24] = array[5136+23-:24];
    reversedArray[5232+23-:24] = array[5112+23-:24];
    reversedArray[5256+23-:24] = array[5088+23-:24];
    reversedArray[5280+23-:24] = array[5064+23-:24];
    reversedArray[5304+23-:24] = array[5040+23-:24];
    reversedArray[5328+23-:24] = array[5016+23-:24];
    reversedArray[5352+23-:24] = array[4992+23-:24];
    reversedArray[5760+23-:24] = array[6120+23-:24];
    reversedArray[5784+23-:24] = array[6096+23-:24];
    reversedArray[5808+23-:24] = array[6072+23-:24];
    reversedArray[5832+23-:24] = array[6048+23-:24];
    reversedArray[5856+23-:24] = array[6024+23-:24];
    reversedArray[5880+23-:24] = array[6000+23-:24];
    reversedArray[5904+23-:24] = array[5976+23-:24];
    reversedArray[5928+23-:24] = array[5952+23-:24];
    reversedArray[5952+23-:24] = array[5928+23-:24];
    reversedArray[5976+23-:24] = array[5904+23-:24];
    reversedArray[6000+23-:24] = array[5880+23-:24];
    reversedArray[6024+23-:24] = array[5856+23-:24];
    reversedArray[6048+23-:24] = array[5832+23-:24];
    reversedArray[6072+23-:24] = array[5808+23-:24];
    reversedArray[6096+23-:24] = array[5784+23-:24];
    reversedArray[6120+23-:24] = array[5760+23-:24];
    out = reversedArray;
  end
endmodule
